2021-04-06 15:08:36.806 [error] <0.311.0> Failed to start Ranch listener 'Elixir.Websocket.Router.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,4000}]) for reason eaddrinuse (address already in use)
2021-04-06 15:13:57.642 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_init/1 line 24
2021-04-06 15:13:57.642 [error] <0.443.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_init/1 line 24
2021-04-06 15:14:26.380 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_init/1 line 24
2021-04-06 15:14:26.380 [error] <0.443.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_init/1 line 24
2021-04-06 15:14:50.682 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_init/1 line 24
2021-04-06 15:14:50.682 [error] <0.443.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_init/1 line 24
2021-04-06 15:15:02.560 [error] <0.445.0> CRASH REPORT Process <0.445.0> with 0 neighbours crashed with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_init/1 line 24
2021-04-06 15:15:02.561 [error] <0.445.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_init/1 line 24
2021-04-06 15:15:05.616 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_handle/2 line 56
2021-04-06 15:15:05.618 [error] <0.443.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_handle/2 line 56
2021-04-06 15:15:14.074 [error] <0.445.0> CRASH REPORT Process <0.445.0> with 0 neighbours crashed with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_handle/2 line 56
2021-04-06 15:15:14.074 [error] <0.445.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_handle/2 line 56
2021-04-06 15:15:53.517 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_handle/2 line 56
2021-04-06 15:15:53.518 [error] <0.443.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_handle/2 line 56
2021-04-06 15:16:31.045 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_handle/2 line 57
2021-04-06 15:16:31.045 [error] <0.443.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_handle/2 line 57
2021-04-06 15:16:51.383 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_handle/2 line 56
2021-04-06 15:16:51.384 [error] <0.443.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_handle/2 line 56
2021-04-06 15:20:36.646 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'messages' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{subscribe,{'basic.consume',0,<<"messages">>,<<>>,false,true,false,false,[]},<0.460.0>},60000]}} in gen_server:call/3 line 246
2021-04-06 15:20:36.646 [error] <0.443.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'messages' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{subscribe,{'basic.consume',0,<<"messages">>,<<>>,false,true,false,false,[]},<0.460.0>},60000]}}
2021-04-06 15:21:38.300 [error] <0.444.0> CRASH REPORT Process <0.444.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'messages' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{subscribe,{'basic.consume',0,<<"messages">>,<<>>,false,true,false,false,[]},<0.460.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-06 15:21:38.304 [error] <0.444.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.443.0> had its request process exit with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'messages' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{subscribe,{'basic.consume',0,<<"messages">>,<<>>,false,true,false,false,[]},<0.460.0>},60000]}} in gen_server:call/3 line 246
2021-04-06 15:25:26.624 [error] <0.444.0> CRASH REPORT Process <0.444.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'messages' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{subscribe,{'basic.consume',0,<<"messages">>,<<>>,false,true,false,false,[]},<0.460.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-06 15:25:26.629 [error] <0.444.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.443.0> had its request process exit with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'messages' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{subscribe,{'basic.consume',0,<<"messages">>,<<>>,false,true,false,false,[]},<0.460.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 18:40:19.202 [error] <0.322.0> Failed to start Ranch listener 'Elixir.Websocket.Router.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,4000}]) for reason eaddrinuse (address already in use)
2021-04-07 18:40:19.208 [error] <0.320.0> Supervisor {<0.320.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link('Elixir.Websocket.Router.HTTP', ranch_tcp) at undefined exit with reason {listen_error,'Elixir.Websocket.Router.HTTP',eaddrinuse} in context start_error
2021-04-07 18:43:02.261 [error] <0.509.0> CRASH REPORT Process <0.509.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'messages' in vhost '/'">>}},{gen_server,call,[<0.521.0>,{subscribe,{'basic.consume',0,<<"messages">>,<<>>,false,true,false,false,[]},<0.523.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-07 18:43:02.288 [error] <0.509.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.507.0> had its request process exit with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'messages' in vhost '/'">>}},{gen_server,call,[<0.521.0>,{subscribe,{'basic.consume',0,<<"messages">>,<<>>,false,true,false,false,[]},<0.523.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 18:55:40.466 [error] <0.444.0> CRASH REPORT Process <0.444.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'websocket_test_exchange' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{call,{'queue.bind',0,<<"websocket_test_queue">>,<<"websocket_test_exchange">>,<<>>,false,[]},none,<0.444.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-07 18:55:40.470 [error] <0.444.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.443.0> had its request process exit with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'websocket_test_exchange' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{call,{'queue.bind',0,<<"websocket_test_queue">>,<<"websocket_test_exchange">>,<<>>,false,[]},none,<0.444.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 18:56:33.069 [error] <0.444.0> CRASH REPORT Process <0.444.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'websocket_test_queue' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{call,{'queue.bind',0,<<"websocket_test_queue">>,<<"websocket_test_exchange">>,<<>>,false,[]},none,<0.444.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-07 18:56:33.075 [error] <0.444.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.443.0> had its request process exit with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'websocket_test_queue' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{call,{'queue.bind',0,<<"websocket_test_queue">>,<<"websocket_test_exchange">>,<<>>,false,[]},none,<0.444.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 18:57:36.863 [error] <0.444.0> CRASH REPORT Process <0.444.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'websocket_test_queue' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{call,{'queue.bind',0,<<"websocket_test_queue">>,<<"websocket_test_exchange">>,<<>>,false,[]},none,<0.444.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-07 18:57:36.866 [error] <0.444.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.443.0> had its request process exit with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'websocket_test_queue' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{call,{'queue.bind',0,<<"websocket_test_queue">>,<<"websocket_test_exchange">>,<<>>,false,[]},none,<0.444.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 19:08:25.084 [error] <0.492.0> gen_server <0.492.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2021-04-07 19:08:25.086 [error] <0.492.0> CRASH REPORT Process <0.492.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2021-04-07 19:08:25.087 [error] <0.493.0> gen_server <0.493.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.492.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-0vhlEQQzbbsqHaK3Cie5Qg">>,1,false,<<"websocket_test_exchange">>,<<>>},{amqp_msg,{'P_basic',undefined,undefined,undefined,1,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"fuck you">>}},60000]}} in gen_server2:call/3 line 346
2021-04-07 19:08:25.087 [error] <0.491.0> Supervisor {<0.491.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:57547 -> 127.0.0.1:5672">>,1}) at <0.492.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2021-04-07 19:08:25.087 [error] <0.491.0> Supervisor {<0.491.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:57547 -> 127.0.0.1:5672">>,1}) at <0.492.0> exit with reason reached_max_restart_intensity in context shutdown
2021-04-07 19:17:46.156 [error] <0.554.0> CRASH REPORT Process <0.554.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.566.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.554.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-07 19:17:46.159 [error] <0.554.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.553.0> had its request process exit with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.566.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.554.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 19:18:21.864 [error] <0.573.0> CRASH REPORT Process <0.573.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.585.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.573.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-07 19:18:21.864 [error] <0.573.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.572.0> had its request process exit with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.585.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.573.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 19:20:42.705 [error] <0.443.0> gen_server <0.443.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2021-04-07 19:20:42.708 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2021-04-07 19:20:42.708 [error] <0.442.0> Supervisor {<0.442.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:51507 -> 127.0.0.1:5672">>,1}) at <0.443.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2021-04-07 19:20:42.708 [error] <0.442.0> Supervisor {<0.442.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:51507 -> 127.0.0.1:5672">>,1}) at <0.443.0> exit with reason reached_max_restart_intensity in context shutdown
2021-04-07 19:56:15.371 [error] <0.317.0> CRASH REPORT Process <0.317.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"could not fetch application environment :port for application :websocket because configuration at :port was not set">>} in 'Elixir.Application':'fetch_env!'/2 line 656 in application_master:init/4 line 138
2021-04-07 20:02:59.526 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.457.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.443.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-07 20:02:59.529 [error] <0.443.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.442.0> had its request process exit with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.457.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.443.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 20:03:28.876 [error] <0.465.0> CRASH REPORT Process <0.465.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.477.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.465.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-07 20:03:28.893 [error] <0.465.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.464.0> had its request process exit with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.477.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.465.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 20:03:28.909 [error] <0.480.0> CRASH REPORT Process <0.480.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.492.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.480.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-07 20:03:28.910 [error] <0.480.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.479.0> had its request process exit with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.492.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.480.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 20:03:44.087 [error] <0.322.0> Failed to start Ranch listener 'Elixir.Websocket.Router.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,4001}]) for reason eaddrinuse (address already in use)
2021-04-07 20:03:44.091 [error] <0.320.0> Supervisor {<0.320.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link('Elixir.Websocket.Router.HTTP', ranch_tcp) at undefined exit with reason {listen_error,'Elixir.Websocket.Router.HTTP',eaddrinuse} in context start_error
2021-04-07 20:04:36.639 [error] <0.442.0> CRASH REPORT Process <0.442.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.456.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.442.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-07 20:04:36.662 [error] <0.442.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.441.0> had its request process exit with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.456.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.442.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 20:08:36.825 [error] <0.456.0> gen_server <0.456.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2021-04-07 20:08:36.828 [error] <0.456.0> CRASH REPORT Process <0.456.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2021-04-07 20:08:36.828 [error] <0.455.0> Supervisor {<0.455.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:32783 -> 127.0.0.1:5672">>,1}) at <0.456.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2021-04-07 20:08:36.828 [error] <0.455.0> Supervisor {<0.455.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:32783 -> 127.0.0.1:5672">>,1}) at <0.456.0> exit with reason reached_max_restart_intensity in context shutdown
2021-04-07 20:09:53.857 [error] <0.456.0> gen_server <0.456.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2021-04-07 20:09:53.863 [error] <0.456.0> CRASH REPORT Process <0.456.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2021-04-07 20:09:53.863 [error] <0.455.0> Supervisor {<0.455.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:54693 -> 127.0.0.1:5672">>,1}) at <0.456.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2021-04-07 20:09:53.863 [error] <0.455.0> Supervisor {<0.455.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:54693 -> 127.0.0.1:5672">>,1}) at <0.456.0> exit with reason reached_max_restart_intensity in context shutdown
