2021-04-06 15:08:36.806 [error] <0.311.0> Failed to start Ranch listener 'Elixir.Websocket.Router.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,4000}]) for reason eaddrinuse (address already in use)
2021-04-06 15:13:57.642 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_init/1 line 24
2021-04-06 15:13:57.642 [error] <0.443.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_init/1 line 24
2021-04-06 15:14:26.380 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_init/1 line 24
2021-04-06 15:14:26.380 [error] <0.443.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_init/1 line 24
2021-04-06 15:14:50.682 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_init/1 line 24
2021-04-06 15:14:50.682 [error] <0.443.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_init/1 line 24
2021-04-06 15:15:02.560 [error] <0.445.0> CRASH REPORT Process <0.445.0> with 0 neighbours crashed with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_init/1 line 24
2021-04-06 15:15:02.561 [error] <0.445.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_init/1 line 24
2021-04-06 15:15:05.616 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_handle/2 line 56
2021-04-06 15:15:05.618 [error] <0.443.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_handle/2 line 56
2021-04-06 15:15:14.074 [error] <0.445.0> CRASH REPORT Process <0.445.0> with 0 neighbours crashed with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_handle/2 line 56
2021-04-06 15:15:14.074 [error] <0.445.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_handle/2 line 56
2021-04-06 15:15:53.517 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_handle/2 line 56
2021-04-06 15:15:53.518 [error] <0.443.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_handle/2 line 56
2021-04-06 15:16:31.045 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_handle/2 line 57
2021-04-06 15:16:31.045 [error] <0.443.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_handle/2 line 57
2021-04-06 15:16:51.383 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_handle/2 line 56
2021-04-06 15:16:51.384 [error] <0.443.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: {badkey,channel,#{registry_key => <<"/ws/chat">>}} in 'Elixir.Websocket.SocketHandler':websocket_handle/2 line 56
2021-04-06 15:20:36.646 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'messages' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{subscribe,{'basic.consume',0,<<"messages">>,<<>>,false,true,false,false,[]},<0.460.0>},60000]}} in gen_server:call/3 line 246
2021-04-06 15:20:36.646 [error] <0.443.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'messages' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{subscribe,{'basic.consume',0,<<"messages">>,<<>>,false,true,false,false,[]},<0.460.0>},60000]}}
2021-04-06 15:21:38.300 [error] <0.444.0> CRASH REPORT Process <0.444.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'messages' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{subscribe,{'basic.consume',0,<<"messages">>,<<>>,false,true,false,false,[]},<0.460.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-06 15:21:38.304 [error] <0.444.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.443.0> had its request process exit with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'messages' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{subscribe,{'basic.consume',0,<<"messages">>,<<>>,false,true,false,false,[]},<0.460.0>},60000]}} in gen_server:call/3 line 246
2021-04-06 15:25:26.624 [error] <0.444.0> CRASH REPORT Process <0.444.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'messages' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{subscribe,{'basic.consume',0,<<"messages">>,<<>>,false,true,false,false,[]},<0.460.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-06 15:25:26.629 [error] <0.444.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.443.0> had its request process exit with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'messages' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{subscribe,{'basic.consume',0,<<"messages">>,<<>>,false,true,false,false,[]},<0.460.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 18:40:19.202 [error] <0.322.0> Failed to start Ranch listener 'Elixir.Websocket.Router.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,4000}]) for reason eaddrinuse (address already in use)
2021-04-07 18:40:19.208 [error] <0.320.0> Supervisor {<0.320.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link('Elixir.Websocket.Router.HTTP', ranch_tcp) at undefined exit with reason {listen_error,'Elixir.Websocket.Router.HTTP',eaddrinuse} in context start_error
2021-04-07 18:43:02.261 [error] <0.509.0> CRASH REPORT Process <0.509.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'messages' in vhost '/'">>}},{gen_server,call,[<0.521.0>,{subscribe,{'basic.consume',0,<<"messages">>,<<>>,false,true,false,false,[]},<0.523.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-07 18:43:02.288 [error] <0.509.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.507.0> had its request process exit with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'messages' in vhost '/'">>}},{gen_server,call,[<0.521.0>,{subscribe,{'basic.consume',0,<<"messages">>,<<>>,false,true,false,false,[]},<0.523.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 18:55:40.466 [error] <0.444.0> CRASH REPORT Process <0.444.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'websocket_test_exchange' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{call,{'queue.bind',0,<<"websocket_test_queue">>,<<"websocket_test_exchange">>,<<>>,false,[]},none,<0.444.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-07 18:55:40.470 [error] <0.444.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.443.0> had its request process exit with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'websocket_test_exchange' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{call,{'queue.bind',0,<<"websocket_test_queue">>,<<"websocket_test_exchange">>,<<>>,false,[]},none,<0.444.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 18:56:33.069 [error] <0.444.0> CRASH REPORT Process <0.444.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'websocket_test_queue' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{call,{'queue.bind',0,<<"websocket_test_queue">>,<<"websocket_test_exchange">>,<<>>,false,[]},none,<0.444.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-07 18:56:33.075 [error] <0.444.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.443.0> had its request process exit with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'websocket_test_queue' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{call,{'queue.bind',0,<<"websocket_test_queue">>,<<"websocket_test_exchange">>,<<>>,false,[]},none,<0.444.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 18:57:36.863 [error] <0.444.0> CRASH REPORT Process <0.444.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'websocket_test_queue' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{call,{'queue.bind',0,<<"websocket_test_queue">>,<<"websocket_test_exchange">>,<<>>,false,[]},none,<0.444.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-07 18:57:36.866 [error] <0.444.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.443.0> had its request process exit with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'websocket_test_queue' in vhost '/'">>}},{gen_server,call,[<0.458.0>,{call,{'queue.bind',0,<<"websocket_test_queue">>,<<"websocket_test_exchange">>,<<>>,false,[]},none,<0.444.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 19:08:25.084 [error] <0.492.0> gen_server <0.492.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2021-04-07 19:08:25.086 [error] <0.492.0> CRASH REPORT Process <0.492.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2021-04-07 19:08:25.087 [error] <0.493.0> gen_server <0.493.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.492.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-0vhlEQQzbbsqHaK3Cie5Qg">>,1,false,<<"websocket_test_exchange">>,<<>>},{amqp_msg,{'P_basic',undefined,undefined,undefined,1,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"fuck you">>}},60000]}} in gen_server2:call/3 line 346
2021-04-07 19:08:25.087 [error] <0.491.0> Supervisor {<0.491.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:57547 -> 127.0.0.1:5672">>,1}) at <0.492.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2021-04-07 19:08:25.087 [error] <0.491.0> Supervisor {<0.491.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:57547 -> 127.0.0.1:5672">>,1}) at <0.492.0> exit with reason reached_max_restart_intensity in context shutdown
2021-04-07 19:17:46.156 [error] <0.554.0> CRASH REPORT Process <0.554.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.566.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.554.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-07 19:17:46.159 [error] <0.554.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.553.0> had its request process exit with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.566.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.554.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 19:18:21.864 [error] <0.573.0> CRASH REPORT Process <0.573.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.585.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.573.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-07 19:18:21.864 [error] <0.573.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.572.0> had its request process exit with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.585.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.573.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 19:20:42.705 [error] <0.443.0> gen_server <0.443.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2021-04-07 19:20:42.708 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2021-04-07 19:20:42.708 [error] <0.442.0> Supervisor {<0.442.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:51507 -> 127.0.0.1:5672">>,1}) at <0.443.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2021-04-07 19:20:42.708 [error] <0.442.0> Supervisor {<0.442.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:51507 -> 127.0.0.1:5672">>,1}) at <0.443.0> exit with reason reached_max_restart_intensity in context shutdown
2021-04-07 19:56:15.371 [error] <0.317.0> CRASH REPORT Process <0.317.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"could not fetch application environment :port for application :websocket because configuration at :port was not set">>} in 'Elixir.Application':'fetch_env!'/2 line 656 in application_master:init/4 line 138
2021-04-07 20:02:59.526 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.457.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.443.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-07 20:02:59.529 [error] <0.443.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.442.0> had its request process exit with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.457.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.443.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 20:03:28.876 [error] <0.465.0> CRASH REPORT Process <0.465.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.477.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.465.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-07 20:03:28.893 [error] <0.465.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.464.0> had its request process exit with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.477.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.465.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 20:03:28.909 [error] <0.480.0> CRASH REPORT Process <0.480.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.492.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.480.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-07 20:03:28.910 [error] <0.480.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.479.0> had its request process exit with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.492.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.480.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 20:03:44.087 [error] <0.322.0> Failed to start Ranch listener 'Elixir.Websocket.Router.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,4001}]) for reason eaddrinuse (address already in use)
2021-04-07 20:03:44.091 [error] <0.320.0> Supervisor {<0.320.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link('Elixir.Websocket.Router.HTTP', ranch_tcp) at undefined exit with reason {listen_error,'Elixir.Websocket.Router.HTTP',eaddrinuse} in context start_error
2021-04-07 20:04:36.639 [error] <0.442.0> CRASH REPORT Process <0.442.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.456.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.442.0>},60000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-07 20:04:36.662 [error] <0.442.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.441.0> had its request process exit with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'websocket_test_queue' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.456.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,true,false,false,[]},none,<0.442.0>},60000]}} in gen_server:call/3 line 246
2021-04-07 20:08:36.825 [error] <0.456.0> gen_server <0.456.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2021-04-07 20:08:36.828 [error] <0.456.0> CRASH REPORT Process <0.456.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2021-04-07 20:08:36.828 [error] <0.455.0> Supervisor {<0.455.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:32783 -> 127.0.0.1:5672">>,1}) at <0.456.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2021-04-07 20:08:36.828 [error] <0.455.0> Supervisor {<0.455.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:32783 -> 127.0.0.1:5672">>,1}) at <0.456.0> exit with reason reached_max_restart_intensity in context shutdown
2021-04-07 20:09:53.857 [error] <0.456.0> gen_server <0.456.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2021-04-07 20:09:53.863 [error] <0.456.0> CRASH REPORT Process <0.456.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2021-04-07 20:09:53.863 [error] <0.455.0> Supervisor {<0.455.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:54693 -> 127.0.0.1:5672">>,1}) at <0.456.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2021-04-07 20:09:53.863 [error] <0.455.0> Supervisor {<0.455.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:54693 -> 127.0.0.1:5672">>,1}) at <0.456.0> exit with reason reached_max_restart_intensity in context shutdown
2021-04-08 13:30:42.877 [error] <0.333.0> Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link(<<>>) at undefined exit with reason {'EXIT',{undef,[{'Elixir.Websocket.AMQPConsumer',start_link,[<<>>],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,...}]}} in context start_error
2021-04-08 13:30:42.877 [error] <0.331.0> CRASH REPORT Process <0.331.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Websocket.AMQPConsumer',{'EXIT',{undef,[{'Elixir.Websocket.AMQPConsumer',start_link,[<<>>],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,...},...]}}}},...} in application_master:init/4 line 138
2021-04-08 13:32:19.374 [error] <0.465.0> CRASH REPORT Process <0.465.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'websocket_test_exchange' in vhost '/': received 'false' but current is 'true'">>}},{gen_server,call,[<0.477.0>,{call,{'exchange.declare',0,<<"websocket_test_exchange">>,<<"fanout">>,false,false,false,false,false,[]},none,<0.465.0>},70000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-08 13:32:19.379 [error] <0.465.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.464.0> had its request process exit with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'websocket_test_exchange' in vhost '/': received 'false' but current is 'true'">>}},{gen_server,call,[<0.477.0>,{call,{'exchange.declare',0,<<"websocket_test_exchange">>,<<"fanout">>,false,false,false,false,false,[]},none,<0.465.0>},70000]}} in gen_server:call/3 line 246
2021-04-08 13:33:21.602 [error] <0.334.0> Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'websocket_test_queue' in vhost '/': received 'false' but current is 'true'">>}},{gen_server,call,[<0.452.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,false,false,false,false,[]},none,<0.438.0>},70000]}} in context start_error
2021-04-08 13:35:53.440 [error] <0.334.0> Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'websocket_test_exchange' in vhost '/': received 'false' but current is 'true'">>}},{gen_server,call,[<0.452.0>,{call,{'exchange.declare',0,<<"websocket_test_exchange">>,<<"fanout">>,false,false,false,false,false,[]},none,<0.438.0>},70000]}} in context start_error
2021-04-08 13:35:53.441 [error] <0.438.0> CRASH REPORT Process <0.438.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'websocket_test_exchange' in vhost '/': received 'false' but current is 'true'">>}},{gen_server,call,[<0.452.0>,{call,{'exchange.declare',0,<<"websocket_test_exchange">>,<<"fanout">>,false,false,false,false,false,[]},none,<0.438.0>},70000]}} in gen_server:call/3 line 246
2021-04-08 13:36:32.296 [error] <0.334.0> Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'x-dead-letter-exchange' for queue 'websocket_test_queue' in vhost '/': received none but current is the value '' of type 'longstr'">>}},{gen_server,call,[<0.452.0>,{call,{'queue.declare',0,<<"websocket_test_queue">>,false,true,false,false,false,[]},none,<0.438.0>},70000]}} in context start_error
2021-04-08 13:37:31.038 [error] <0.460.0> CRASH REPORT Process <0.460.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'websocket_test_exchange' in vhost '/': received 'false' but current is 'true'">>}},{gen_server,call,[<0.472.0>,{call,{'exchange.declare',0,<<"websocket_test_exchange">>,<<"fanout">>,false,false,false,false,false,[]},none,<0.460.0>},70000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-08 13:37:31.041 [error] <0.460.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.459.0> had its request process exit with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'websocket_test_exchange' in vhost '/': received 'false' but current is 'true'">>}},{gen_server,call,[<0.472.0>,{call,{'exchange.declare',0,<<"websocket_test_exchange">>,<<"fanout">>,false,false,false,false,false,[]},none,<0.460.0>},70000]}} in gen_server:call/3 line 246
2021-04-08 13:38:49.372 [error] <0.460.0> CRASH REPORT Process <0.460.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'chatter_test_exchange' in vhost '/': received 'false' but current is 'true'">>}},{gen_server,call,[<0.472.0>,{call,{'exchange.declare',0,<<"chatter_test_exchange">>,<<"fanout">>,false,false,false,false,false,[]},none,<0.460.0>},70000]}} in gen_server:call/3 line 246 in gen_server:call/3 line 246
2021-04-08 13:38:49.376 [error] <0.460.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.459.0> had its request process exit with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'chatter_test_exchange' in vhost '/': received 'false' but current is 'true'">>}},{gen_server,call,[<0.472.0>,{call,{'exchange.declare',0,<<"chatter_test_exchange">>,<<"fanout">>,false,false,false,false,false,[]},none,<0.460.0>},70000]}} in gen_server:call/3 line 246
2021-04-08 13:40:04.525 [error] <0.471.0> gen_server <0.471.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2021-04-08 13:40:04.543 [error] <0.471.0> CRASH REPORT Process <0.471.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2021-04-08 13:40:04.543 [error] <0.470.0> Supervisor {<0.470.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:33421 -> 127.0.0.1:5672">>,1}) at <0.471.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2021-04-08 13:40:04.550 [error] <0.470.0> Supervisor {<0.470.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:33421 -> 127.0.0.1:5672">>,1}) at <0.471.0> exit with reason reached_max_restart_intensity in context shutdown
2021-04-08 13:40:12.621 [error] <0.459.0>@gen_server:call CRASH REPORT Process <0.459.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.472.0>, {call,{'basic.publish',0,<<"chatter_test_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,...},...},...}, 70000) in gen_server:call/3 line 246
2021-04-08 13:40:12.621 [error] <0.459.0>@gen_server:call Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: no such process or port in call to gen_server:call(<0.472.0>, {call,{'basic.publish',0,<<"chatter_test_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,...},...},...}, 70000)
2021-04-08 13:41:28.529 [error] <0.487.0> gen_server <0.487.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2021-04-08 13:41:28.529 [error] <0.487.0> CRASH REPORT Process <0.487.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2021-04-08 13:41:28.533 [error] <0.488.0> gen_server <0.488.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.487.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-A2fxMDLePdf-BS-Hzhw2yw">>,1,false,<<"chatter_test_exchange">>,<<>>},{amqp_msg,{'P_basic',undefined,undefined,undefined,1,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"blah blah blah">>}},70000]}} in gen_server2:call/3 line 346
2021-04-08 13:41:28.536 [error] <0.486.0> Supervisor {<0.486.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:53241 -> 127.0.0.1:5672">>,1}) at <0.487.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2021-04-08 13:41:28.537 [error] <0.486.0> Supervisor {<0.486.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:53241 -> 127.0.0.1:5672">>,1}) at <0.487.0> exit with reason reached_max_restart_intensity in context shutdown
2021-04-08 13:43:38.597 [error] <0.456.0> gen_server <0.456.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2021-04-08 13:43:38.604 [error] <0.456.0> CRASH REPORT Process <0.456.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2021-04-08 13:43:38.605 [error] <0.455.0> Supervisor {<0.455.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:50235 -> 127.0.0.1:5672">>,1}) at <0.456.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2021-04-08 13:43:38.606 [error] <0.455.0> Supervisor {<0.455.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:50235 -> 127.0.0.1:5672">>,1}) at <0.456.0> exit with reason reached_max_restart_intensity in context shutdown
2021-04-08 13:44:26.081 [error] <0.444.0>@gen_server:call CRASH REPORT Process <0.444.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.457.0>, {call,{'basic.publish',0,<<"chatter_test_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,...},...},...}, 70000) in gen_server:call/3 line 246
2021-04-08 13:44:26.082 [error] <0.444.0>@gen_server:call Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: no such process or port in call to gen_server:call(<0.457.0>, {call,{'basic.publish',0,<<"chatter_test_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,...},...},...}, 70000)
2021-04-08 13:48:22.627 [error] <0.457.0> gen_server <0.457.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2021-04-08 13:48:22.662 [error] <0.457.0> CRASH REPORT Process <0.457.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2021-04-08 13:48:22.663 [error] <0.456.0> Supervisor {<0.456.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:55921 -> 127.0.0.1:5672">>,1}) at <0.457.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2021-04-08 13:48:22.663 [error] <0.456.0> Supervisor {<0.456.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:55921 -> 127.0.0.1:5672">>,1}) at <0.457.0> exit with reason reached_max_restart_intensity in context shutdown
2021-04-08 13:50:07.010 [error] <0.459.0>@cowboy_websocket:handler_call:526 CRASH REPORT Process <0.459.0> with 0 neighbours crashed with reason: no try clause matching {noreply,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.463.0>},custom_consumer => nil,pid => <0.472.0>},registry_key => <<"/ws/chat">>}} in cowboy_websocket:handler_call/6 line 526
2021-04-08 13:50:07.012 [error] <0.459.0>@cowboy_websocket:handler_call:526 Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: no try clause matching {noreply,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.463.0>},custom_consumer => nil,pid => <0.472.0>},registry_key => <<"/ws/chat">>}} in cowboy_websocket:handler_call/6 line 526
2021-04-08 13:50:22.727 [error] <0.459.0>@cowboy_websocket:handler_call:526 CRASH REPORT Process <0.459.0> with 0 neighbours crashed with reason: no try clause matching {noreply,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.463.0>},custom_consumer => nil,pid => <0.472.0>},registry_key => <<"/ws/chat">>}} in cowboy_websocket:handler_call/6 line 526
2021-04-08 13:50:22.727 [error] <0.459.0>@cowboy_websocket:handler_call:526 Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: no try clause matching {noreply,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.463.0>},custom_consumer => nil,pid => <0.472.0>},registry_key => <<"/ws/chat">>}} in cowboy_websocket:handler_call/6 line 526
2021-04-08 13:50:25.534 [error] <0.475.0>@cowboy_websocket:handler_call:526 CRASH REPORT Process <0.475.0> with 0 neighbours crashed with reason: no try clause matching {noreply,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.479.0>},custom_consumer => nil,pid => <0.488.0>},registry_key => <<"/ws/chat">>}} in cowboy_websocket:handler_call/6 line 526
2021-04-08 13:50:25.536 [error] <0.475.0>@cowboy_websocket:handler_call:526 Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: no try clause matching {noreply,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.479.0>},custom_consumer => nil,pid => <0.488.0>},registry_key => <<"/ws/chat">>}} in cowboy_websocket:handler_call/6 line 526
2021-04-08 13:50:31.803 [error] <0.491.0>@cowboy_websocket:handler_call:526 CRASH REPORT Process <0.491.0> with 0 neighbours crashed with reason: no try clause matching {noreply,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.495.0>},custom_consumer => nil,pid => <0.504.0>},registry_key => <<"/ws/chat">>}} in cowboy_websocket:handler_call/6 line 526
2021-04-08 13:50:31.807 [error] <0.491.0>@cowboy_websocket:handler_call:526 Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: no try clause matching {noreply,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.495.0>},custom_consumer => nil,pid => <0.504.0>},registry_key => <<"/ws/chat">>}} in cowboy_websocket:handler_call/6 line 526
2021-04-08 13:50:45.295 [error] <0.507.0>@cowboy_websocket:handler_call:526 CRASH REPORT Process <0.507.0> with 0 neighbours crashed with reason: no try clause matching {noreply,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.511.0>},custom_consumer => nil,pid => <0.520.0>},registry_key => <<"/ws/chat">>}} in cowboy_websocket:handler_call/6 line 526
2021-04-08 13:50:45.296 [error] <0.507.0>@cowboy_websocket:handler_call:526 Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: no try clause matching {noreply,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.511.0>},custom_consumer => nil,pid => <0.520.0>},registry_key => <<"/ws/chat">>}} in cowboy_websocket:handler_call/6 line 526
2021-04-08 13:53:15.409 [error] <0.471.0> gen_server <0.471.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2021-04-08 13:53:15.412 [error] <0.471.0> CRASH REPORT Process <0.471.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2021-04-08 13:53:15.412 [error] <0.470.0> Supervisor {<0.470.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:46409 -> 127.0.0.1:5672">>,1}) at <0.471.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2021-04-08 13:53:15.412 [error] <0.470.0> Supervisor {<0.470.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:46409 -> 127.0.0.1:5672">>,1}) at <0.471.0> exit with reason reached_max_restart_intensity in context shutdown
2021-04-08 14:04:42.652 [error] <0.471.0> gen_server <0.471.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2021-04-08 14:04:42.667 [error] <0.471.0> CRASH REPORT Process <0.471.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2021-04-08 14:04:42.667 [error] <0.470.0> Supervisor {<0.470.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:38355 -> 127.0.0.1:5672">>,1}) at <0.471.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2021-04-08 14:04:42.668 [error] <0.470.0> Supervisor {<0.470.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:38355 -> 127.0.0.1:5672">>,1}) at <0.471.0> exit with reason reached_max_restart_intensity in context shutdown
2021-04-08 14:26:47.413 [error] <0.459.0> CRASH REPORT Process <0.459.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Poison.EncodeError',message => nil,value => <0.459.0>} in 'Elixir.Poison.Encoder.Any':encode/2 line 383
2021-04-08 14:26:47.413 [error] <0.459.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Poison.EncodeError',message => nil,value => <0.459.0>} in 'Elixir.Poison.Encoder.Any':encode/2 line 383
2021-04-08 14:36:42.072 [error] <0.438.0> gen_server <0.438.0> terminated with reason: {badkey,registry_key,#{<<"message">> => <<"Hello server!">>,<<"registry_key">> => <<"/ws/chat">>}} in 'Elixir.Websocket.AMQPConsumer':handle_info/2 line 54
2021-04-08 14:36:42.076 [error] <0.438.0> CRASH REPORT Process <0.438.0> with 0 neighbours crashed with reason: {badkey,registry_key,#{<<"message">> => <<"Hello server!">>,<<"registry_key">> => <<"/ws/chat">>}} in 'Elixir.Websocket.AMQPConsumer':handle_info/2 line 54
2021-04-08 14:36:42.076 [error] <0.334.0> Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at <0.438.0> exit with reason {badkey,registry_key,#{<<"message">> => <<"Hello server!">>,<<"registry_key">> => <<"/ws/chat">>}} in 'Elixir.Websocket.AMQPConsumer':handle_info/2 line 54 in context child_terminated
2021-04-08 14:37:06.752 [error] <0.438.0> gen_server <0.438.0> terminated with reason: {badkey,registry_key,#{<<"message">> => <<"Hello server!">>,<<"registry_key">> => <<"/ws/chat">>}} in 'Elixir.Websocket.AMQPConsumer':handle_info/2 line 55
2021-04-08 14:37:06.760 [error] <0.438.0> CRASH REPORT Process <0.438.0> with 0 neighbours crashed with reason: {badkey,registry_key,#{<<"message">> => <<"Hello server!">>,<<"registry_key">> => <<"/ws/chat">>}} in 'Elixir.Websocket.AMQPConsumer':handle_info/2 line 55
2021-04-08 14:37:06.761 [error] <0.334.0> Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at <0.438.0> exit with reason {badkey,registry_key,#{<<"message">> => <<"Hello server!">>,<<"registry_key">> => <<"/ws/chat">>}} in 'Elixir.Websocket.AMQPConsumer':handle_info/2 line 55 in context child_terminated
2021-04-08 14:38:00.135 [error] <0.438.0> gen_server <0.438.0> terminated with reason: {badkey,registry_key,#{<<"message">> => <<"Hello server!">>,<<"registry_key">> => <<"/ws/chat">>}} in 'Elixir.Websocket.AMQPConsumer':handle_info/2 line 56
2021-04-08 14:38:00.152 [error] <0.438.0> CRASH REPORT Process <0.438.0> with 0 neighbours crashed with reason: {badkey,registry_key,#{<<"message">> => <<"Hello server!">>,<<"registry_key">> => <<"/ws/chat">>}} in 'Elixir.Websocket.AMQPConsumer':handle_info/2 line 56
2021-04-08 14:38:00.153 [error] <0.334.0> Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at <0.438.0> exit with reason {badkey,registry_key,#{<<"message">> => <<"Hello server!">>,<<"registry_key">> => <<"/ws/chat">>}} in 'Elixir.Websocket.AMQPConsumer':handle_info/2 line 56 in context child_terminated
2021-04-08 14:39:06.936 [error] <0.438.0> gen_server <0.438.0> terminated with reason: {badkey,registry_key,#{<<"message">> => <<"Hello server!">>,<<"registry_key">> => <<"/ws/chat">>}} in 'Elixir.Websocket.AMQPConsumer':handle_info/2 line 54
2021-04-08 14:39:06.946 [error] <0.438.0> CRASH REPORT Process <0.438.0> with 0 neighbours crashed with reason: {badkey,registry_key,#{<<"message">> => <<"Hello server!">>,<<"registry_key">> => <<"/ws/chat">>}} in 'Elixir.Websocket.AMQPConsumer':handle_info/2 line 54
2021-04-08 14:39:06.946 [error] <0.334.0> Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at <0.438.0> exit with reason {badkey,registry_key,#{<<"message">> => <<"Hello server!">>,<<"registry_key">> => <<"/ws/chat">>}} in 'Elixir.Websocket.AMQPConsumer':handle_info/2 line 54 in context child_terminated
2021-04-08 14:42:56.238 [error] <0.465.0>@Elixir.Websocket.SocketHandler:websocket_info CRASH REPORT Process <0.465.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.Websocket.SocketHandler':websocket_info(<<"Hello server!">>, #{registry_key => <<"/ws/chat">>})
2021-04-08 14:42:56.239 [error] <0.465.0>@Elixir.Websocket.SocketHandler:websocket_info Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: call to undefined function 'Elixir.Websocket.SocketHandler':websocket_info(<<"Hello server!">>, #{registry_key => <<"/ws/chat">>})
2021-04-08 14:43:06.526 [error] <0.444.0>@Elixir.Websocket.SocketHandler:websocket_info CRASH REPORT Process <0.444.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.Websocket.SocketHandler':websocket_info(<<"Hello server!">>, #{registry_key => <<"/ws/chat">>})
2021-04-08 14:43:06.526 [error] <0.444.0>@Elixir.Websocket.SocketHandler:websocket_info Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: call to undefined function 'Elixir.Websocket.SocketHandler':websocket_info(<<"Hello server!">>, #{registry_key => <<"/ws/chat">>})
2021-04-08 14:43:13.425 [error] <0.459.0>@Elixir.Websocket.SocketHandler:websocket_info CRASH REPORT Process <0.459.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.Websocket.SocketHandler':websocket_info(<<"Hello server!">>, #{registry_key => <<"/ws/chat">>})
2021-04-08 14:43:13.425 [error] <0.459.0>@Elixir.Websocket.SocketHandler:websocket_info Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: call to undefined function 'Elixir.Websocket.SocketHandler':websocket_info(<<"Hello server!">>, #{registry_key => <<"/ws/chat">>})
2021-04-08 15:00:53.691 [error] <0.459.0> CRASH REPORT Process <0.459.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"Registry.update_value/3 is not supported for duplicate registries">>} in 'Elixir.Registry':update_value/3 line 430
2021-04-08 15:00:53.691 [error] <0.459.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"Registry.update_value/3 is not supported for duplicate registries">>} in 'Elixir.Registry':update_value/3 line 430
2021-04-08 15:24:19.008 [error] <0.337.0> Failed to start Ranch listener 'Elixir.Websocket.Router.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,4000}]) for reason eaddrinuse (address already in use)
2021-04-08 15:24:33.598 [error] <0.322.0> Failed to start Ranch listener 'Elixir.Websocket.Router.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,4000}]) for reason eaddrinuse (address already in use)
2021-04-08 17:06:55.201 [error] <0.446.0>@Elixir.GenRegistry:lookup CRASH REPORT Process <0.446.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.GenRegistry':lookup('Elixir.Websocket.AMQPConsumer')
2021-04-08 17:06:55.207 [error] <0.446.0>@Elixir.GenRegistry:lookup Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.445.0> had its request process exit with reason: call to undefined function 'Elixir.GenRegistry':lookup('Elixir.Websocket.AMQPConsumer')
2021-04-08 17:24:44.149 [error] <0.324.0> Failed to start Ranch listener 'Elixir.Websocket.Router.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,4000}]) for reason eaddrinuse (address already in use)
2021-04-08 17:24:44.182 [error] <0.322.0> Supervisor {<0.322.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link('Elixir.Websocket.Router.HTTP', ranch_tcp) at undefined exit with reason {listen_error,'Elixir.Websocket.Router.HTTP',eaddrinuse} in context start_error
2021-04-08 17:24:44.182 [error] <0.324.0> CRASH REPORT Process <0.324.0> with 0 neighbours exited with reason: {listen_error,'Elixir.Websocket.Router.HTTP',eaddrinuse} in ranch_acceptors_sup:listen_error/5 line 66
2021-04-08 17:28:31.490 [error] <0.451.0> gen_server amqp terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer :amqp but no handle_call/3 clause was provided">>} in 'Elixir.Websocket.AMQPConsumer':handle_call/3 line 777
2021-04-08 17:28:31.511 [error] <0.451.0> CRASH REPORT Process amqp with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer :amqp but no handle_call/3 clause was provided">>} in 'Elixir.Websocket.AMQPConsumer':handle_call/3 line 777
2021-04-08 17:28:31.512 [error] <0.347.0> Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at <0.451.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer :amqp but no handle_call/3 clause was provided">>} in 'Elixir.Websocket.AMQPConsumer':handle_call/3 line 777 in context child_terminated
2021-04-08 17:28:31.512 [error] <0.473.0> CRASH REPORT Process <0.473.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer :amqp but no handle_call/3 clause was provided">>},[{'Elixir.Websocket.AMQPConsumer',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,715}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,744}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[amqp,{get_state},5000]}} in 'Elixir.GenServer':call/3 line 1027 in 'Elixir.GenServer':call/3 line 1027
2021-04-08 17:28:31.519 [error] <0.473.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.472.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer :amqp but no handle_call/3 clause was provided">>},[{'Elixir.Websocket.AMQPConsumer',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,715}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,744}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[amqp,{get_state},5000]}} in 'Elixir.GenServer':call/3 line 1027
2021-04-08 17:31:29.421 [error] <0.441.0> gen_server amqp terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer :amqp but no handle_call/3 clause was provided">>} in 'Elixir.Websocket.AMQPConsumer':handle_call/3 line 777
2021-04-08 17:31:29.429 [error] <0.441.0> CRASH REPORT Process amqp with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer :amqp but no handle_call/3 clause was provided">>} in 'Elixir.Websocket.AMQPConsumer':handle_call/3 line 777
2021-04-08 17:31:29.430 [error] <0.337.0> Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at <0.441.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer :amqp but no handle_call/3 clause was provided">>} in 'Elixir.Websocket.AMQPConsumer':handle_call/3 line 777 in context child_terminated
2021-04-08 17:31:29.430 [error] <0.463.0> CRASH REPORT Process <0.463.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer :amqp but no handle_call/3 clause was provided">>},[{'Elixir.Websocket.AMQPConsumer',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,715}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,744}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[amqp,{get_state},5000]}} in 'Elixir.GenServer':call/3 line 1027 in 'Elixir.GenServer':call/3 line 1027
2021-04-08 17:31:29.442 [error] <0.463.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.462.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer :amqp but no handle_call/3 clause was provided">>},[{'Elixir.Websocket.AMQPConsumer',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,715}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,744}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[amqp,{get_state},5000]}} in 'Elixir.GenServer':call/3 line 1027
2021-04-08 17:32:07.508 [error] <0.441.0> gen_server amqp terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer :amqp but no handle_call/3 clause was provided">>} in 'Elixir.Websocket.AMQPConsumer':handle_call/3 line 777
2021-04-08 17:32:07.516 [error] <0.441.0> CRASH REPORT Process amqp with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer :amqp but no handle_call/3 clause was provided">>} in 'Elixir.Websocket.AMQPConsumer':handle_call/3 line 777
2021-04-08 17:32:07.517 [error] <0.337.0> Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at <0.441.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer :amqp but no handle_call/3 clause was provided">>} in 'Elixir.Websocket.AMQPConsumer':handle_call/3 line 777 in context child_terminated
2021-04-08 17:32:07.517 [error] <0.463.0> CRASH REPORT Process <0.463.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer :amqp but no handle_call/3 clause was provided">>},[{'Elixir.Websocket.AMQPConsumer',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,715}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,744}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[amqp,{get_state},5000]}} in 'Elixir.GenServer':call/3 line 1027 in 'Elixir.GenServer':call/3 line 1027
2021-04-08 17:32:07.521 [error] <0.463.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.462.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer :amqp but no handle_call/3 clause was provided">>},[{'Elixir.Websocket.AMQPConsumer',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,715}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,744}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[amqp,{get_state},5000]}} in 'Elixir.GenServer':call/3 line 1027
2021-04-08 17:32:55.632 [error] <0.463.0> CRASH REPORT Process <0.463.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => <0.441.0>} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2021-04-08 17:32:55.639 [error] <0.463.0> Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.462.0> had its request process exit with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => <0.441.0>} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2021-04-08 17:33:29.343 [error] <0.463.0>@Elixir.GenRegistry:lookup:74 CRASH REPORT Process <0.463.0> with 0 neighbours crashed with reason: bad argument in call to ets:lookup('Elixir.Websocket.AMQPConsumer', 'Elixir.MyAMQP') in 'Elixir.GenRegistry':lookup/2 line 74
2021-04-08 17:33:29.346 [error] <0.463.0>@Elixir.GenRegistry:lookup:74 Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.462.0> had its request process exit with reason: bad argument in call to ets:lookup('Elixir.Websocket.AMQPConsumer', 'Elixir.MyAMQP') in 'Elixir.GenRegistry':lookup/2 line 74
2021-04-09 10:41:45.003 [error] <0.445.0> gen_server amqp terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => <0.466.0>} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2021-04-09 10:41:45.007 [error] <0.445.0> CRASH REPORT Process amqp with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => <0.466.0>} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2021-04-09 10:41:45.008 [error] <0.341.0> Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at <0.445.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => <0.466.0>} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2021-04-09 10:42:37.700 [error] <0.445.0>@Elixir.Websocket.AMQPConsumer:handle_info:68 gen_server amqp terminated with reason: bad argument in call to erlang:byte_size(<0.445.0>) in 'Elixir.Websocket.AMQPConsumer':handle_info/2 line 68
2021-04-09 10:42:37.708 [error] <0.445.0>@Elixir.Websocket.AMQPConsumer:handle_info:68 CRASH REPORT Process amqp with 0 neighbours crashed with reason: bad argument in call to erlang:byte_size(<0.445.0>) in 'Elixir.Websocket.AMQPConsumer':handle_info/2 line 68
2021-04-09 10:42:37.708 [error] <0.341.0>@Elixir.Websocket.AMQPConsumer:handle_info:68 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at <0.445.0> exit with reason bad argument in call to erlang:byte_size(<0.445.0>) in 'Elixir.Websocket.AMQPConsumer':handle_info/2 line 68 in context child_terminated
2021-04-09 10:59:52.690 [error] <0.455.0> Failed to start Ranch listener 'Elixir.Websocket.Router.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,4001}]) for reason eaddrinuse (address already in use)
2021-04-09 11:00:22.319 [error] <0.326.0> Failed to start Ranch listener 'Elixir.Websocket.Router.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,4001}]) for reason eaddrinuse (address already in use)
2021-04-09 11:08:08.851 [error] <0.341.0> Failed to start Ranch listener 'Elixir.Websocket.Router.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,4001}]) for reason eaddrinuse (address already in use)
2021-04-09 11:08:17.804 [error] <0.441.0>@Elixir.Websocket.AMQPConsumer:init:30 CRASH REPORT Process <0.441.0> with 0 neighbours crashed with reason: bad argument in call to erlang:byte_size("<0.441.0>") in 'Elixir.Websocket.AMQPConsumer':init/1 line 30
2021-04-12 14:50:29.864 [error] <0.463.0>@cow_ws:payload_length:725 CRASH REPORT Process <0.463.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_size(#{<<"message">> => <<"Hello server!">>,<<"user">> => <<"Ethelind">>}) in cow_ws:payload_length/1 line 725
2021-04-12 14:50:29.864 [error] <0.463.0>@cow_ws:payload_length:725 Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: bad argument in call to erlang:iolist_size(#{<<"message">> => <<"Hello server!">>,<<"user">> => <<"Ethelind">>}) in cow_ws:payload_length/1 line 725
2021-04-12 14:50:55.469 [error] <0.463.0>@cow_ws:payload_length:725 CRASH REPORT Process <0.463.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_size(#{<<"message">> => <<"Hello server!">>,<<"user">> => <<"Selene">>}) in cow_ws:payload_length/1 line 725
2021-04-12 14:50:55.471 [error] <0.463.0>@cow_ws:payload_length:725 Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: bad argument in call to erlang:iolist_size(#{<<"message">> => <<"Hello server!">>,<<"user">> => <<"Selene">>}) in cow_ws:payload_length/1 line 725
2021-04-12 14:51:20.330 [error] <0.465.0>@cow_ws:payload_length:725 CRASH REPORT Process <0.465.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_size(#{<<"message">> => <<"Hello server!">>,<<"user">> => <<"Talya">>}) in cow_ws:payload_length/1 line 725
2021-04-12 14:51:20.330 [error] <0.465.0>@cow_ws:payload_length:725 Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: bad argument in call to erlang:iolist_size(#{<<"message">> => <<"Hello server!">>,<<"user">> => <<"Talya">>}) in cow_ws:payload_length/1 line 725
2021-04-12 14:52:14.582 [error] <0.463.0>@cow_ws:frame:633 CRASH REPORT Process <0.463.0> with 0 neighbours crashed with reason: no function clause matching cow_ws:frame({text,<<"Hello server!">>,<<"Aigneis">>}, #{}) line 633
2021-04-12 14:52:14.583 [error] <0.463.0>@cow_ws:frame:633 Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: no function clause matching cow_ws:frame({text,<<"Hello server!">>,<<"Aigneis">>}, #{}) line 633
2021-04-12 16:06:41.433 [error] <0.494.0>@Elixir.Websocket.SocketHandler:init:10 CRASH REPORT Process <0.494.0> with 0 neighbours crashed with reason: bad argument in call to erlang:byte_size(#{<<"origin">> => <<"47.229.32.79">>}) in 'Elixir.Websocket.SocketHandler':init/2 line 10
2021-04-12 16:06:41.447 [error] <0.494.0>@Elixir.Websocket.SocketHandler:init:10 Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.493.0> had its request process exit with reason: bad argument in call to erlang:byte_size(#{<<"origin">> => <<"47.229.32.79">>}) in 'Elixir.Websocket.SocketHandler':init/2 line 10
2021-04-12 16:07:09.267 [error] <0.494.0>@Elixir.Websocket.SocketHandler:init:10 CRASH REPORT Process <0.494.0> with 0 neighbours crashed with reason: bad argument in call to erlang:byte_size(#{<<"origin">> => <<"47.229.32.79">>}) in 'Elixir.Websocket.SocketHandler':init/2 line 10
2021-04-12 16:07:09.272 [error] <0.494.0>@Elixir.Websocket.SocketHandler:init:10 Cowboy stream 1 with ranch listener 'Elixir.Websocket.Router.HTTP' and connection process <0.493.0> had its request process exit with reason: bad argument in call to erlang:byte_size(#{<<"origin">> => <<"47.229.32.79">>}) in 'Elixir.Websocket.SocketHandler':init/2 line 10
2021-04-12 19:16:56.352 [error] <0.353.0> Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"could not fetch application environment :rabbitmq_host for application :websocket because configuration at :rabbitmq_host was not set">>} in 'Elixir.Application':'fetch_env!'/2 line 656 in context start_error
2021-04-12 19:17:13.708 [error] <0.353.0> Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"could not fetch application environment :rabbitmq_host for application :websocket because configuration at :rabbitmq_host was not set">>} in 'Elixir.Application':'fetch_env!'/2 line 656 in context start_error
2021-04-12 19:17:15.494 [error] <0.353.0> Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"could not fetch application environment :rabbitmq_host for application :websocket because configuration at :rabbitmq_host was not set">>} in 'Elixir.Application':'fetch_env!'/2 line 656 in context start_error
2021-04-12 19:18:14.811 [error] <0.353.0> Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"could not fetch application environment :rabbitmq_host for application :websocket because configuration at :rabbitmq_host was not set">>} in 'Elixir.Application':'fetch_env!'/2 line 656 in context start_error
2021-04-12 19:19:25.382 [error] <0.538.0> CRASH REPORT Process <0.538.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:19:25.382 [error] <0.538.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:19:26.163 [error] <0.532.0>@Elixir.Websocket.AMQPConsumer:init:22 CRASH REPORT Process <0.532.0> with 0 neighbours crashed with reason: no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 22
2021-04-12 19:19:26.163 [error] <0.428.0>@Elixir.Websocket.AMQPConsumer:init:22 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 22 in context start_error
2021-04-12 19:19:26.165 [error] <0.426.0> CRASH REPORT Process <0.426.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Websocket.AMQPConsumer',{{badmatch,{error,timeout}},[{'Elixir.Websocket.AMQPConsumer',init,1,[{file,"lib/amqp_consumer.ex"},{line,22}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{'Elixir.Websocket.Application',start,[normal,[]]}} in application_master:init/4 line 138
2021-04-12 19:27:51.976 [error] <0.368.0>@Elixir.Websocket.AMQPConsumer:init:23 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,{auth_failure,"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile."}} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23 in context start_error
2021-04-12 19:37:28.371 [error] <0.368.0>@Elixir.Websocket.AMQPConsumer:init:23 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,not_allowed} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23 in context start_error
2021-04-12 19:37:53.455 [error] <0.472.0>@Elixir.Websocket.AMQPConsumer:init:23 CRASH REPORT Process <0.472.0> with 0 neighbours crashed with reason: no match of right hand value {error,{auth_failure,"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile."}} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23
2021-04-12 19:37:53.455 [error] <0.368.0>@Elixir.Websocket.AMQPConsumer:init:23 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,{auth_failure,"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile."}} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23 in context start_error
2021-04-12 19:37:53.456 [error] <0.366.0> CRASH REPORT Process <0.366.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Websocket.AMQPConsumer',{{badmatch,{error,{auth_failure,"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile."}}},[{'Elixir.Websocket.AMQPConsumer',init,1,[{file,"lib/amqp_consumer.ex"},{line,23}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{'Elixir.Websocket.Application',...}} in application_master:init/4 line 138
2021-04-12 19:42:27.679 [error] <0.368.0>@Elixir.Websocket.AMQPConsumer:init:23 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,not_allowed} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23 in context start_error
2021-04-12 19:42:27.679 [error] <0.472.0>@Elixir.Websocket.AMQPConsumer:init:23 CRASH REPORT Process <0.472.0> with 0 neighbours crashed with reason: no match of right hand value {error,not_allowed} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23
2021-04-12 19:42:27.682 [error] <0.366.0> CRASH REPORT Process <0.366.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Websocket.AMQPConsumer',{{badmatch,{error,not_allowed}},[{'Elixir.Websocket.AMQPConsumer',init,1,[{file,"lib/amqp_consumer.ex"},{line,23}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{'Elixir.Websocket.Application',start,[normal,[]]}} in application_master:init/4 line 138
2021-04-12 19:44:58.915 [error] <0.538.0> CRASH REPORT Process <0.538.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:44:58.915 [error] <0.538.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:45:47.277 [error] <0.428.0>@Elixir.Websocket.AMQPConsumer:init:23 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23 in context start_error
2021-04-12 19:45:47.278 [error] <0.532.0>@Elixir.Websocket.AMQPConsumer:init:23 CRASH REPORT Process <0.532.0> with 0 neighbours crashed with reason: no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23
2021-04-12 19:46:52.336 [error] <0.463.0> CRASH REPORT Process <0.463.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:46:52.336 [error] <0.463.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:47:37.212 [error] <0.457.0>@Elixir.Websocket.AMQPConsumer:init:23 CRASH REPORT Process <0.457.0> with 0 neighbours crashed with reason: no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23
2021-04-12 19:49:37.383 [error] <0.483.0> CRASH REPORT Process <0.483.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:37.387 [error] <0.483.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:37.481 [error] <0.490.0> CRASH REPORT Process <0.490.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:37.481 [error] <0.490.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:37.584 [error] <0.493.0> CRASH REPORT Process <0.493.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:37.584 [error] <0.493.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:39.283 [error] <0.496.0> CRASH REPORT Process <0.496.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:39.283 [error] <0.496.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:39.386 [error] <0.499.0> CRASH REPORT Process <0.499.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:39.387 [error] <0.499.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:39.484 [error] <0.502.0> CRASH REPORT Process <0.502.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:39.484 [error] <0.502.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:40.788 [error] <0.505.0> CRASH REPORT Process <0.505.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:40.788 [error] <0.505.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:40.892 [error] <0.508.0> CRASH REPORT Process <0.508.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:40.892 [error] <0.508.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:41.000 [error] <0.511.0> CRASH REPORT Process <0.511.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:41.000 [error] <0.511.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:42.526 [error] <0.514.0> CRASH REPORT Process <0.514.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:42.526 [error] <0.514.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:42.638 [error] <0.517.0> CRASH REPORT Process <0.517.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:42.638 [error] <0.517.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:42.746 [error] <0.520.0> CRASH REPORT Process <0.520.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:49:42.746 [error] <0.520.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:50:34.038 [error] <0.373.0>@Elixir.Websocket.AMQPConsumer:init:23 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23 in context start_error
2021-04-12 19:50:34.038 [error] <0.477.0>@Elixir.Websocket.AMQPConsumer:init:23 CRASH REPORT Process <0.477.0> with 0 neighbours crashed with reason: no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23
2021-04-12 19:50:34.040 [error] <0.371.0> CRASH REPORT Process <0.371.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Websocket.AMQPConsumer',{{badmatch,{error,timeout}},[{'Elixir.Websocket.AMQPConsumer',init,1,[{file,"lib/amqp_consumer.ex"},{line,23}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{'Elixir.Websocket.Application',start,[normal,[]]}} in application_master:init/4 line 138
2021-04-12 19:53:41.894 [error] <0.463.0> CRASH REPORT Process <0.463.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:53:41.895 [error] <0.463.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:54:31.341 [error] <0.457.0>@Elixir.Websocket.AMQPConsumer:init:23 CRASH REPORT Process <0.457.0> with 0 neighbours crashed with reason: no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23
2021-04-12 19:54:31.341 [error] <0.353.0>@Elixir.Websocket.AMQPConsumer:init:23 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23 in context start_error
2021-04-12 19:54:31.344 [error] <0.351.0> CRASH REPORT Process <0.351.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Websocket.AMQPConsumer',{{badmatch,{error,timeout}},[{'Elixir.Websocket.AMQPConsumer',init,1,[{file,"lib/amqp_consumer.ex"},{line,23}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{'Elixir.Websocket.Application',start,[normal,[]]}} in application_master:init/4 line 138
2021-04-12 19:55:55.085 [error] <0.478.0> CRASH REPORT Process <0.478.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 19:55:55.086 [error] <0.478.0> Ranch listener 'Elixir.Websocket.Router.HTTP' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.MyWebsocketApp">>} in 'Elixir.Registry':'info!'/1 line 1267
2021-04-12 20:00:05.967 [error] <0.532.0>@Elixir.Websocket.AMQPConsumer:init:23 CRASH REPORT Process <0.532.0> with 0 neighbours crashed with reason: no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23
2021-04-12 20:00:05.967 [error] <0.428.0>@Elixir.Websocket.AMQPConsumer:init:23 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23 in context start_error
2021-04-12 20:05:23.094 [error] <0.353.0>@Elixir.Websocket.AMQPConsumer:init:23 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23 in context start_error
2021-04-12 20:05:23.094 [error] <0.457.0>@Elixir.Websocket.AMQPConsumer:init:23 CRASH REPORT Process <0.457.0> with 0 neighbours crashed with reason: no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23
2021-04-12 20:05:23.098 [error] <0.351.0> CRASH REPORT Process <0.351.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Websocket.AMQPConsumer',{{badmatch,{error,timeout}},[{'Elixir.Websocket.AMQPConsumer',init,1,[{file,"lib/amqp_consumer.ex"},{line,23}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{'Elixir.Websocket.Application',start,[normal,[]]}} in application_master:init/4 line 138
2021-04-12 20:07:09.909 [error] <0.353.0>@Elixir.Websocket.AMQPConsumer:init:23 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23 in context start_error
2021-04-12 20:07:09.910 [error] <0.457.0>@Elixir.Websocket.AMQPConsumer:init:23 CRASH REPORT Process <0.457.0> with 0 neighbours crashed with reason: no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23
2021-04-12 20:07:09.912 [error] <0.351.0> CRASH REPORT Process <0.351.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Websocket.AMQPConsumer',{{badmatch,{error,timeout}},[{'Elixir.Websocket.AMQPConsumer',init,1,[{file,"lib/amqp_consumer.ex"},{line,23}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{'Elixir.Websocket.Application',start,[normal,[]]}} in application_master:init/4 line 138
2021-04-12 20:10:38.211 [error] <0.353.0>@Elixir.Websocket.AMQPConsumer:init:23 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23 in context start_error
2021-04-12 20:10:38.211 [error] <0.457.0>@Elixir.Websocket.AMQPConsumer:init:23 CRASH REPORT Process <0.457.0> with 0 neighbours crashed with reason: no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23
2021-04-12 20:10:38.215 [error] <0.351.0> CRASH REPORT Process <0.351.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Websocket.AMQPConsumer',{{badmatch,{error,timeout}},[{'Elixir.Websocket.AMQPConsumer',init,1,[{file,"lib/amqp_consumer.ex"},{line,23}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{'Elixir.Websocket.Application',start,[normal,[]]}} in application_master:init/4 line 138
2021-04-12 20:12:01.630 [error] <0.428.0>@Elixir.Websocket.AMQPConsumer:init:23 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,{server_sent_malformed_header,<<"HTTP/1.">>}} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23 in context start_error
2021-04-12 20:13:11.891 [error] <0.353.0>@Elixir.Websocket.AMQPConsumer:init:23 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,{server_sent_malformed_header,<<"HTTP/1.">>}} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23 in context start_error
2021-04-12 20:20:15.726 [error] <0.428.0>@Elixir.Websocket.AMQPConsumer:init:23 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,{server_sent_malformed_header,<<"HTTP/1.">>}} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23 in context start_error
2021-04-12 20:20:15.726 [error] <0.532.0>@Elixir.Websocket.AMQPConsumer:init:23 CRASH REPORT Process <0.532.0> with 0 neighbours crashed with reason: no match of right hand value {error,{server_sent_malformed_header,<<"HTTP/1.">>}} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23
2021-04-12 20:20:15.732 [error] <0.426.0> CRASH REPORT Process <0.426.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Websocket.AMQPConsumer',{{badmatch,{error,{server_sent_malformed_header,<<"HTTP/1.">>}}},[{'Elixir.Websocket.AMQPConsumer',init,1,[{file,"lib/amqp_consumer.ex"},{line,23}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{'Elixir.Websocket.Application',start,[normal,[]]}} in application_master:init/4 line 138
2021-04-12 20:23:48.535 [error] <0.428.0>@Elixir.Websocket.AMQPConsumer:init:23 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,econnrefused} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23 in context start_error
2021-04-12 20:23:48.535 [error] <0.532.0>@Elixir.Websocket.AMQPConsumer:init:23 CRASH REPORT Process <0.532.0> with 0 neighbours crashed with reason: no match of right hand value {error,econnrefused} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23
2021-04-12 20:34:35.649 [error] <0.368.0>@Elixir.Websocket.AMQPConsumer:init:24 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,{auth_failure,"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile."}} in 'Elixir.Websocket.AMQPConsumer':init/1 line 24 in context start_error
2021-04-12 20:35:16.801 [error] <0.368.0>@Elixir.Websocket.AMQPConsumer:init:24 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,{socket_closed_unexpectedly,'connection.start'}} in 'Elixir.Websocket.AMQPConsumer':init/1 line 24 in context start_error
2021-04-12 20:35:16.802 [error] <0.472.0>@Elixir.Websocket.AMQPConsumer:init:24 CRASH REPORT Process <0.472.0> with 0 neighbours crashed with reason: no match of right hand value {error,{socket_closed_unexpectedly,'connection.start'}} in 'Elixir.Websocket.AMQPConsumer':init/1 line 24
2021-04-12 20:35:23.299 [error] <0.368.0>@Elixir.Websocket.AMQPConsumer:init:24 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,{socket_closed_unexpectedly,'connection.start'}} in 'Elixir.Websocket.AMQPConsumer':init/1 line 24 in context start_error
2021-04-12 20:41:21.793 [error] <0.371.0> Failed to start Ranch listener 'Elixir.Websocket.Router.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,4001}]) for reason eaddrinuse (address already in use)
2021-04-12 20:43:09.696 [error] <0.353.0>@Elixir.Websocket.AMQPConsumer:init:23 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23 in context start_error
2021-04-12 20:43:09.696 [error] <0.457.0>@Elixir.Websocket.AMQPConsumer:init:23 CRASH REPORT Process <0.457.0> with 0 neighbours crashed with reason: no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23
2021-04-12 20:44:11.656 [error] <0.353.0>@Elixir.Websocket.AMQPConsumer:init:23 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23 in context start_error
2021-04-12 20:44:11.656 [error] <0.457.0>@Elixir.Websocket.AMQPConsumer:init:23 CRASH REPORT Process <0.457.0> with 0 neighbours crashed with reason: no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23
2021-04-12 20:46:13.455 [error] <0.428.0>@Elixir.Websocket.AMQPConsumer:init:23 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 23 in context start_error
2021-04-12 20:52:14.796 [error] <0.368.0>@Elixir.Websocket.AMQPConsumer:init:24 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 24 in context start_error
2021-04-12 20:52:14.796 [error] <0.472.0>@Elixir.Websocket.AMQPConsumer:init:24 CRASH REPORT Process <0.472.0> with 0 neighbours crashed with reason: no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 24
2021-04-12 20:52:14.799 [error] <0.366.0> CRASH REPORT Process <0.366.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Websocket.AMQPConsumer',{{badmatch,{error,timeout}},[{'Elixir.Websocket.AMQPConsumer',init,1,[{file,"lib/amqp_consumer.ex"},{line,24}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{'Elixir.Websocket.Application',start,[normal,[]]}} in application_master:init/4 line 138
2021-04-12 20:57:43.975 [error] <0.353.0>@Elixir.Websocket.AMQPConsumer:init:24 Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 24 in context start_error
2021-04-12 20:57:43.975 [error] <0.457.0>@Elixir.Websocket.AMQPConsumer:init:24 CRASH REPORT Process <0.457.0> with 0 neighbours crashed with reason: no match of right hand value {error,timeout} in 'Elixir.Websocket.AMQPConsumer':init/1 line 24
2021-04-12 20:57:43.977 [error] <0.351.0> CRASH REPORT Process <0.351.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Websocket.AMQPConsumer',{{badmatch,{error,timeout}},[{'Elixir.Websocket.AMQPConsumer',init,1,[{file,"lib/amqp_consumer.ex"},{line,24}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{'Elixir.Websocket.Application',start,[normal,[]]}} in application_master:init/4 line 138
2021-04-13 12:16:43.363 [error] <0.428.0> Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at undefined exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"could not fetch application environment :APP_ID for application :websocket because configuration at :APP_ID was not set">>} in 'Elixir.Application':'fetch_env!'/2 line 656 in context start_error
2021-04-13 12:22:13.808 [error] <0.368.0> Supervisor 'Elixir.Websocket.Supervisor' had child 'Elixir.Websocket.AMQPConsumer' started with 'Elixir.Websocket.AMQPConsumer':start_link([]) at <0.472.0> exit with reason normal in context child_terminated
